/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paralelaproyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author omar_
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    public String user, nombre, apellido;
    public String passwd;
    public int Type, carrera, semestre, matricula ,ciclo, turno, grupo, id_alumno;
    private final DefaultComboBoxModel carreraModel;
    private final DefaultComboBoxModel turnoModel;
    private final DefaultComboBoxModel cicloModel;
    private final DefaultComboBoxModel semestreModel;
    private final DefaultComboBoxModel grupoModel;
    ArrayList array = new ArrayList();
    DefaultListModel model =  new DefaultListModel();
    ArrayList array2 = new ArrayList();
    DefaultListModel model2 =  new DefaultListModel();
    Connection conexion;
    Statement s;
    
    private int tipoUsuario;
    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin() {
        initComponents();
        carreraModel = new DefaultComboBoxModel(new String[] {}); //modelo de carrera
        turnoModel = new DefaultComboBoxModel(new String[] {});
        cicloModel =  new DefaultComboBoxModel(new String[] {});
        semestreModel = new DefaultComboBoxModel(new String[] {});
        grupoModel =  new DefaultComboBoxModel(new String[] {});
        ListaEliminados.setModel(model);
        ListaDatos.setModel(model2);
        CarreraComboBox.setModel(carreraModel);
        turnoComboBox.setModel(turnoModel);
        cicloJComboBox.setModel(cicloModel);
        SemestrecomboBox.setModel(semestreModel);
        GrupoComboBox.setModel(grupoModel);
        jTabbedPane1.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
              if(ce.getSource() instanceof JTabbedPane) {
                  JTabbedPane pane = (JTabbedPane)ce.getSource();
                  System.out.println("Selected pane NO: " + pane.getSelectedIndex());
                  if(pane.getSelectedIndex() == 2)
                    {
                      LlenarLista();
                      
                    }
                  //if(pane.getSelectedIndex() == 1)
                      
              } 
            }
        });
        try {
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
             conexion = DriverManager.getConnection ("jdbc:mysql://localhost/proyecto","root", "");
            s = conexion.createStatement();
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        ButtonGroupTurno = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TypeOfUser = new javax.swing.JList<>();
        UserTextField = new javax.swing.JTextField();
        PasswdTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        SaveUser = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CarreraComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        GrupoComboBox = new javax.swing.JComboBox<>();
        SemestrecomboBox = new javax.swing.JComboBox<>();
        turnoComboBox = new javax.swing.JComboBox<>();
        GuardarDatos = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        apellidoTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cicloJComboBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaEliminados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        EliminarUsuario = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        alumnosRadioButton = new javax.swing.JRadioButton();
        docenteRadioButton = new javax.swing.JRadioButton();
        seRadioButton = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaDatos = new javax.swing.JList<>();
        CicloDatosJLabel = new javax.swing.JLabel();
        CicloDatosTextField = new javax.swing.JTextField();
        SemestreDatosJlabel = new javax.swing.JLabel();
        TurnoDatosJlabel = new javax.swing.JLabel();
        CarreraDatosJlabel = new javax.swing.JLabel();
        TurnoDatosJtext = new javax.swing.JTextField();
        SemestreDatosTextField = new javax.swing.JTextField();
        CarreraDatosTextField = new javax.swing.JTextField();
        GrupoDatosJLabel = new javax.swing.JLabel();
        GrupoDatosTextfield = new javax.swing.JTextField();
        nombreJlabelDatos = new javax.swing.JLabel();
        nombreDatosTextField = new javax.swing.JTextField();
        ApellidoDatosJlabel = new javax.swing.JLabel();
        ApellidoDatosJText = new javax.swing.JTextField();
        MatriculaDatosJLabel = new javax.swing.JLabel();
        MatriculaDatosJtext = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Administrador");
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(null);
        jPanel1.add(Name);
        Name.setBounds(10, 20, 80, 0);

        jButton2.setText("Cerrar Sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 250, 110, 23);

        jTabbedPane1.addTab("Inicio", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Usuario:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jLabel3.setText("Contraseña:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jLabel4.setText("Tipo Usuario:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));

        TypeOfUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Alumno", "Docente", "Servicios Academicos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TypeOfUser.setSelectedIndex(0);
        jScrollPane1.setViewportView(TypeOfUser);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, 116, 74));

        UserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(UserTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 78, -1));
        jPanel2.add(PasswdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, 78, -1));

        jButton3.setText("Cerrar Sesion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, 110, -1));

        SaveUser.setText("Guardar");
        SaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveUserActionPerformed(evt);
            }
        });
        jPanel2.add(SaveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        Reset.setText("Restablecer");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel2.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel10.setVisible(false);
        jLabel10.setText("Turno:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 40, -1));

        jLabel11.setVisible(false);
        jLabel11.setText("Semestre:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 60, -1));

        jLabel12.setVisible(false);
        jLabel12.setText("Carrera:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        CarreraComboBox.setVisible(false);
        CarreraComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CarreraComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarreraComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(CarreraComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel13.setVisible(false);
        jLabel13.setText("Grupo");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        GrupoComboBox.setVisible(false);
        GrupoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        jPanel2.add(GrupoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        SemestrecomboBox.setVisible(false);
        SemestrecomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel2.add(SemestrecomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 56, -1));

        turnoComboBox.setVisible(false);
        turnoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(turnoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        GuardarDatos.setVisible(false);
        GuardarDatos.setText("Guardar");
        GuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(GuardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel14.setVisible(false);
        jLabel14.setText("Nombre:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 60, -1));

        nombreTextField.setVisible(false);
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 90, -1));

        jLabel15.setVisible(false);
        jLabel15.setText("Apellido:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        apellidoTextField.setVisible(false);
        jPanel2.add(apellidoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 90, -1));

        jLabel16.setVisible(false);
        jLabel16.setText("Ciclo:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 40, -1));

        cicloJComboBox.setVisible(false);
        cicloJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cicloJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        jLabel17.setVisible(false);
        jLabel17.setText("Matricula");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 63, -1));

        matriculaTextField.setVisible(false);
        jPanel2.add(matriculaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, -1));

        jTabbedPane1.addTab("Nuevo Usuario", jPanel2);

        ListaEliminados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaEliminados.setSelectedIndex(0);
        jScrollPane2.setViewportView(ListaEliminados);

        jLabel1.setText("Nombre de Usuario");

        EliminarUsuario.setText("Eliminar");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar Sesion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarUsuario)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(EliminarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Eliminar Usuario", jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 600));

        buttonGroup1.add(alumnosRadioButton);
        alumnosRadioButton.setText("alumnos");
        alumnosRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnosRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(docenteRadioButton);
        docenteRadioButton.setText("Docentes");
        docenteRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docenteRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(seRadioButton);
        seRadioButton.setText("Servicios Escolares");
        seRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seRadioButtonActionPerformed(evt);
            }
        });

        ListaDatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDatosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ListaDatos);

        CicloDatosJLabel.setText("Ciclo");

        CicloDatosTextField.setEditable(false);

        SemestreDatosJlabel.setText("Semestre");

        TurnoDatosJlabel.setText("Turno");

        CarreraDatosJlabel.setText("Carrera");

        TurnoDatosJtext.setEditable(false);

        SemestreDatosTextField.setEditable(false);

        CarreraDatosTextField.setEditable(false);

        GrupoDatosJLabel.setText("Grupo");

        GrupoDatosTextfield.setEditable(false);

        nombreJlabelDatos.setText("Nombre");

        nombreDatosTextField.setEditable(false);

        ApellidoDatosJlabel.setText("Apellido");

        ApellidoDatosJText.setEditable(false);

        MatriculaDatosJLabel.setText("Matricula");

        MatriculaDatosJtext.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(alumnosRadioButton)
                .addGap(45, 45, 45)
                .addComponent(docenteRadioButton)
                .addGap(39, 39, 39)
                .addComponent(seRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(nombreJlabelDatos)
                .addGap(63, 63, 63)
                .addComponent(ApellidoDatosJlabel))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculaDatosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculaDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SemestreDatosJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SemestreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CicloDatosJLabel))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApellidoDatosJText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurnoDatosJlabel)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GrupoDatosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrupoDatosTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarreraDatosJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarreraDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(CicloDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TurnoDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnosRadioButton)
                    .addComponent(docenteRadioButton)
                    .addComponent(seRadioButton))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJlabelDatos)
                    .addComponent(ApellidoDatosJlabel))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nombreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(MatriculaDatosJLabel)
                        .addGap(6, 6, 6)
                        .addComponent(MatriculaDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(SemestreDatosJlabel)
                        .addGap(6, 6, 6)
                        .addComponent(SemestreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CicloDatosJLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ApellidoDatosJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(GrupoDatosJLabel)
                        .addGap(6, 6, 6)
                        .addComponent(GrupoDatosTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CarreraDatosJlabel)
                        .addGap(6, 6, 6)
                        .addComponent(CarreraDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TurnoDatosJlabel)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CicloDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurnoDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Consulta datos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveUserActionPerformed
        user = UserTextField.getText();
        passwd = PasswdTextField.getText();
        Type = TypeOfUser.getSelectedIndex() + 2;
        llenarComboBox();
        try {
               
                String SSQL="INSERT INTO `usuarios` (`id_usuario`, `usuario`, `contra`, `tipo_usuario`) VALUES (NULL, '"+user+"', '"+passwd+"', '"+Type+"') ";
                Statement sI = conexion.createStatement();
                sI.executeUpdate(SSQL);
                JOptionPane.showMessageDialog(this, "Usuario Agregado con exito, ingrese los datos a continuacion", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {

                JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }
        switch(Type){
            case 2:
                UserTextField.setText("");
                PasswdTextField.setText("");
                UserTextField.setVisible(false);
                PasswdTextField.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jScrollPane1.setVisible(false);
                SaveUser.setVisible(false);
                TypeOfUser.setVisible(false);
                Reset.setVisible(false);
                jLabel11.setVisible(true);
                turnoComboBox.setVisible(true);
                jLabel10.setVisible(true);
                SemestrecomboBox.setVisible(true);
                cicloJComboBox.setVisible(true);
                jLabel13.setVisible(true);
                GrupoComboBox.setVisible(true);
                jLabel12.setVisible(true);
                jLabel14.setVisible(true);
                jLabel15.setVisible(true);
                jLabel16.setVisible(true);
                jLabel17.setVisible(true);
                matriculaTextField.setVisible(true);
                nombreTextField.setVisible(true);
                apellidoTextField.setVisible(true);
                CarreraComboBox.setVisible(true);
                GuardarDatos.setVisible(true);
       break;
            case 3:
                UserTextField.setText("");
                PasswdTextField.setText("");
                UserTextField.setVisible(false);
                PasswdTextField.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jScrollPane1.setVisible(false);
                SaveUser.setVisible(false);
                TypeOfUser.setVisible(false);
                Reset.setVisible(false);
                jLabel13.setVisible(true);
                GrupoComboBox.setVisible(true);
                jLabel14.setVisible(true);
                jLabel15.setVisible(true);
                jLabel17.setVisible(true);
                nombreTextField.setVisible(true);
                apellidoTextField.setVisible(true);
                matriculaTextField.setVisible(true);
                GuardarDatos.setVisible(true);
                break;
            case 4:
                UserTextField.setText("");
                PasswdTextField.setText("");
                UserTextField.setVisible(false);
                PasswdTextField.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                jScrollPane1.setVisible(false);
                SaveUser.setVisible(false);
                TypeOfUser.setVisible(false);
                Reset.setVisible(false);
                  jLabel14.setVisible(true);
                jLabel15.setVisible(true);
                nombreTextField.setVisible(true);
                apellidoTextField.setVisible(true);
                GuardarDatos.setVisible(true);
                break;
    }
    }//GEN-LAST:event_SaveUserActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
       UserTextField.setText("");
       PasswdTextField.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        String eliminacion = ListaEliminados.getSelectedValue();
         if (JOptionPane.showConfirmDialog(this, "En verdad desea eliminar el usuario: " + eliminacion, "Confirmacion", 
                 JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
             try {
            String SSQL="DELETE FROM `usuarios` WHERE usuario = '"+eliminacion+"' ";
            Statement sE = conexion.createStatement();
            sE.executeUpdate(SSQL);
             JOptionPane.showMessageDialog(this, "Usuario Eliminado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
             LlenarLista();
         
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);
    }
         }
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void alumnosRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnosRadioButtonActionPerformed
        tipoUsuario = 2;
        nombreDatosTextField.setText("");
        ApellidoDatosJText.setText("");
        MatriculaDatosJtext.setText("");
        GrupoDatosTextfield.setText("");
        CarreraDatosTextField.setText("");
        SemestreDatosTextField.setText("");
        CicloDatosTextField.setText("");
        TurnoDatosJtext.setText("");
        SemestreDatosJlabel.setVisible(true);
        SemestreDatosTextField.setVisible(true);
         GrupoDatosJLabel.setVisible(true);
        GrupoDatosTextfield.setVisible(true);
        SemestreDatosJlabel.setVisible(true);
        SemestreDatosTextField.setVisible(true);
        CarreraDatosJlabel.setVisible(true);
        CarreraDatosTextField.setVisible(true);
        CicloDatosJLabel.setVisible(true);
        CicloDatosTextField.setVisible(true);
        TurnoDatosJlabel.setVisible(true);
        TurnoDatosJtext.setVisible(true);
        LlenarListaDatos(tipoUsuario);
    }//GEN-LAST:event_alumnosRadioButtonActionPerformed

    private void docenteRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docenteRadioButtonActionPerformed
        tipoUsuario = 3;
        nombreDatosTextField.setText("");
        ApellidoDatosJText.setText("");
        MatriculaDatosJtext.setText("");
        GrupoDatosTextfield.setText("");
        SemestreDatosJlabel.setVisible(false);
        SemestreDatosTextField.setVisible(false);
        CarreraDatosJlabel.setVisible(false);
        CarreraDatosTextField.setVisible(false);
        CicloDatosJLabel.setVisible(false);
        CicloDatosTextField.setVisible(false);
        TurnoDatosJlabel.setVisible(false);
        TurnoDatosJtext.setVisible(false);
        LlenarListaDatos(tipoUsuario);
        
    }//GEN-LAST:event_docenteRadioButtonActionPerformed

    private void seRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seRadioButtonActionPerformed
        tipoUsuario = 4;
        nombreDatosTextField.setText("");
        ApellidoDatosJText.setText("");
        MatriculaDatosJtext.setText("");
         GrupoDatosJLabel.setVisible(true);
        GrupoDatosTextfield.setVisible(true);
        GrupoDatosJLabel.setVisible(false);
        GrupoDatosTextfield.setVisible(false);
        SemestreDatosJlabel.setVisible(false);
        SemestreDatosTextField.setVisible(false);
        CarreraDatosJlabel.setVisible(false);
        CarreraDatosTextField.setVisible(false);
        CicloDatosJLabel.setVisible(false);
        CicloDatosTextField.setVisible(false);
        TurnoDatosJlabel.setVisible(false);
        TurnoDatosJtext.setVisible(false);
        LlenarListaDatos(tipoUsuario);
        
    }//GEN-LAST:event_seRadioButtonActionPerformed

    private void CarreraComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarreraComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarreraComboBoxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void GuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatosActionPerformed
     
        InsertarDatos(Type);
    }//GEN-LAST:event_GuardarDatosActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void ListaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDatosMouseClicked
         String nomb = (String)ListaDatos.getSelectedValue();
         ConsultarDatos(nomb, tipoUsuario);
         
    }//GEN-LAST:event_ListaDatosMouseClicked

    private void LlenarLista(){
         try {
             model.clear();
            ResultSet rs = s.executeQuery("SELECT * FROM usuarios");
            while(rs.next()) {
                
              model.addElement(rs.getString(2));
              
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     private void LlenarListaDatos(int dato){
         int id;
         try {
             model2.clear();
            ResultSet rs = s.executeQuery("SELECT * FROM usuarios WHERE tipo_usuario= '"+dato+"' ");
            while(rs.next()) {
              
              model2.addElement(rs.getString(2));
              
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
     public void llenarComboBox(){
          try {
            ResultSet rs = s.executeQuery("SELECT * FROM carrera");
            while(rs.next()) {
               carreraModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
           try {
            
            ResultSet rs = s.executeQuery("SELECT * FROM turnos");
            while(rs.next()) {
               turnoModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
             try {
           
            ResultSet rs = s.executeQuery("SELECT * FROM ciclo");
            while(rs.next()) {
               cicloModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
                try {
           
            ResultSet rs = s.executeQuery("SELECT * FROM semestre");
            while(rs.next()) {
               semestreModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
                     try {
           
            ResultSet rs = s.executeQuery("SELECT * FROM grupos");
            while(rs.next()) {
               grupoModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
     }
     private void InsertarDatos(int tipo){
            try {
          
            String SSQL="SELECT * FROM usuarios WHERE usuario='"+user+"'";
            ResultSet rs = s.executeQuery(SSQL);
            if(rs.next()){
            id_alumno = rs.getInt(1);
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
         switch(tipo){
             case 2:
                matricula = Integer.parseInt(matriculaTextField.getText());
                nombre = nombreTextField.getText();
                apellido =  apellidoTextField.getText();
                carrera = CarreraComboBox.getSelectedIndex() + 1;
                semestre = SemestrecomboBox.getSelectedIndex() + 1;
                turno = turnoComboBox.getSelectedIndex() + 1;
                grupo = GrupoComboBox.getSelectedIndex() +1 ;
                ciclo = cicloJComboBox.getSelectedIndex() +1;
                try {
                   
                    String SSQL="INSERT INTO `alumnos` (`id_usuario`, `nombre`, `apellido`, `matricula`,`id_grupo`, `id_semestre`,"
                        + " `id_carrera`, `id_ciclo`, `id_turno` ) VALUES ('"+id_alumno+"', '"+nombre+"', '"+apellido+"'"
                        + ",'"+matricula+"','"+grupo+"','"+semestre+"', '"+carrera+"', '"+ciclo+"', '"+turno+"') ";
                    s.executeUpdate(SSQL);
                    JOptionPane.showMessageDialog(this, "Alumno Agregado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
             case 3:
                 matricula = Integer.parseInt(matriculaTextField.getText());
                 nombre = nombreTextField.getText();
                 apellido =  apellidoTextField.getText();
                 grupo = GrupoComboBox.getSelectedIndex() +1 ;
                 try {
                    
                    String SSQL="INSERT INTO `maestros` (`id_usuario`, `nombre`, `apellido`, `matricula`,`id_grupo`) VALUES ('"+id_alumno+"', '"+nombre+"', '"+apellido+"'"
                        + ",'"+matricula+"','"+grupo+"') ";
                    
                    s.executeUpdate(SSQL);
                    JOptionPane.showMessageDialog(this, "Maestro Agregado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                }
                 break;
             case 4:
                nombre = nombreTextField.getText();
                apellido =  apellidoTextField.getText();
                try {
                    
                    String SSQL="INSERT INTO `serve` (`id_usuario`, `nombre`, `apellido` ) VALUES ('"+id_alumno+"', '"+nombre+"', '"+apellido+"'"
                        + ") ";
                    
                    s.executeUpdate(SSQL);
                    JOptionPane.showMessageDialog(this, "Servicios Escolares Agregado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                }
                break;
         }
     }
     
     public void ConsultarDatos(String nomb, int tipoUsuarioDatos){
        
         int id = 0, Dgrupo = 0, Dsemestre= 0, Dcarrera = 0, Dciclo = 0, Dturno = 0;
         switch(tipoUsuarioDatos){
             case 2:
                    
            try {
            
            ResultSet rs = s.executeQuery("SELECT * FROM usuarios WHERE usuario = '"+nomb+"'");
            while(rs.next()){
                id = rs.getInt(1);
               
            }
             System.out.println(id);
            ResultSet rs1 = s.executeQuery("SELECT * FROM alumnos WHERE id_usuario = '"+id+"'");
            while(rs1.next()){
                nombreDatosTextField.setText(rs1.getString(2));
                ApellidoDatosJText.setText(rs1.getString(3));
                MatriculaDatosJtext.setText(rs1.getString(4));
                Dgrupo = rs1.getInt(5);
                Dsemestre = rs1.getInt(6);
                Dcarrera = rs1.getInt(7);
                Dciclo = rs1.getInt(8);
                Dturno = rs1.getInt(9);
            }
            ResultSet rs2 = s.executeQuery("SELECT * FROM `grupos`,`semestre`,"
                    + " `carrera`, `ciclo` , `turnos` WHERE id_grupo = '"+Dgrupo+"' AND id_carrera = '"+Dcarrera+"' "
                            + "AND id_semestre = '"+Dsemestre+"' AND id_ciclo = '"+Dciclo+"' AND id_turno = '"+Dturno+"'");
            while(rs2.next()){
                GrupoDatosTextfield.setText(rs2.getString(2));
                CarreraDatosTextField.setText(rs2.getString(6));
                SemestreDatosTextField.setText(rs2.getString(4));
                CicloDatosTextField.setText(rs2.getString(8));
                TurnoDatosJtext.setText(rs2.getString(12));
            }
          }catch (SQLException e){
           JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);   
          }
                 break;
             case 3:
                     try {
            
            ResultSet rs = s.executeQuery("SELECT * FROM usuarios WHERE usuario = '"+nomb+"'");
            while(rs.next()){
                id = rs.getInt(1);
               
            }
             System.out.println(id);
            ResultSet rs1 = s.executeQuery("SELECT * FROM maestros WHERE id_usuario = '"+id+"'");
            while(rs1.next()){
                nombreDatosTextField.setText(rs1.getString(2));
                ApellidoDatosJText.setText(rs1.getString(3));
                MatriculaDatosJtext.setText(rs1.getString(4));
                Dgrupo = rs1.getInt(5);
            }
            ResultSet rs2 = s.executeQuery("SELECT * FROM `grupos` WHERE id_grupo = '"+Dgrupo+"' ");
            while(rs2.next()){
                GrupoDatosTextfield.setText(rs2.getString(2));
                
            }
          }catch (SQLException e){
           JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);   
          }
                 break;
             case 4:
                           try {
            
            ResultSet rs = s.executeQuery("SELECT * FROM usuarios WHERE usuario = '"+nomb+"'");
            while(rs.next()){
                id = rs.getInt(1);
               
            }
             System.out.println(id);
            ResultSet rs1 = s.executeQuery("SELECT * FROM serve WHERE id_usuario = '"+id+"'");
            while(rs1.next()){
                nombreDatosTextField.setText(rs1.getString(2));
                ApellidoDatosJText.setText(rs1.getString(3));
               
            }
            
          }catch (SQLException e){
           JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);   
          }
                 break;
         }
     }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoDatosJText;
    private javax.swing.JLabel ApellidoDatosJlabel;
    private javax.swing.ButtonGroup ButtonGroupTurno;
    private javax.swing.JComboBox<String> CarreraComboBox;
    private javax.swing.JLabel CarreraDatosJlabel;
    private javax.swing.JTextField CarreraDatosTextField;
    private javax.swing.JLabel CicloDatosJLabel;
    private javax.swing.JTextField CicloDatosTextField;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JComboBox<String> GrupoComboBox;
    private javax.swing.JLabel GrupoDatosJLabel;
    private javax.swing.JTextField GrupoDatosTextfield;
    private javax.swing.JButton GuardarDatos;
    private javax.swing.JList<String> ListaDatos;
    private javax.swing.JList<String> ListaEliminados;
    private javax.swing.JLabel MatriculaDatosJLabel;
    private javax.swing.JTextField MatriculaDatosJtext;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField PasswdTextField;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SaveUser;
    private javax.swing.JLabel SemestreDatosJlabel;
    private javax.swing.JTextField SemestreDatosTextField;
    private javax.swing.JComboBox<String> SemestrecomboBox;
    private javax.swing.JLabel TurnoDatosJlabel;
    private javax.swing.JTextField TurnoDatosJtext;
    private javax.swing.JList<String> TypeOfUser;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JRadioButton alumnosRadioButton;
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cicloJComboBox;
    private javax.swing.JRadioButton docenteRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JTextField nombreDatosTextField;
    private javax.swing.JLabel nombreJlabelDatos;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JRadioButton seRadioButton;
    private javax.swing.JComboBox<String> turnoComboBox;
    // End of variables declaration//GEN-END:variables
}
