# Generated by Django 2.0.6 on 2018-07-17 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField()),
                ('asunto', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CitaEstatus',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='id_estatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.CitaEstatus'),
        ),
    ]
