# Generated by Django 2.0.6 on 2018-07-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='id_estatus',
            new_name='estatus',
        ),
    ]
