# Generated by Django 2.0.7 on 2018-07-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0003_auto_20180726_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='estatus',
            field=models.CharField(choices=[('1', 'Solicitada'), ('2', 'Aceptada'), ('3', 'Atendida')], default='1', max_length=2),
        ),
        migrations.DeleteModel(
            name='CitaEstatus',
        ),
    ]
