# Generated by Django 2.0.7 on 2018-07-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0004_auto_20180726_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
