# Generated by Django 2.0.7 on 2018-07-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20180726_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='token',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
