# Generated by Django 2.0.7 on 2018-07-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20180726_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(editable=False, help_text='ID unico de cada persona', primary_key=True, serialize=False),
        ),
    ]
