/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paralelaproyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import RMI.RemoteInterface;
import java.rmi.registry.Registry;
import java.rmi.registry.LocateRegistry;
import javax.swing.JComboBox;

/**
 *
 * @author omar_
 */
public class PanelAdmin extends javax.swing.JFrame {
    
    public String user, nombre, apellido;
    public String passwd;
    public int Type, carrera, semestre, matricula ,ciclo, turno, grupo, id_alumno;
    private final DefaultComboBoxModel carreraModel;
    private final DefaultComboBoxModel turnoModel;
    private final DefaultComboBoxModel cicloModel;
    private final DefaultComboBoxModel semestreModel;
    private final DefaultComboBoxModel grupoModel;
    ArrayList array = new ArrayList();
    DefaultListModel model =  new DefaultListModel();
    ArrayList array2 = new ArrayList();
    DefaultListModel model2 =  new DefaultListModel();
     Connection conexion;
    Statement s;
    private int tipoUsuario, idUsuario;
    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin(int id_admin) {
        this.idUsuario = id_admin;
        initComponents();
        carreraModel = new DefaultComboBoxModel(new String[] {});
        turnoModel = new DefaultComboBoxModel(new String[] {});
        cicloModel =  new DefaultComboBoxModel(new String[] {});
        semestreModel = new DefaultComboBoxModel(new String[] {});
        grupoModel =  new DefaultComboBoxModel(new String[] {});
        ListaEliminados.setModel(model);
        ListaDatos.setModel(model2);
        CarreraComboBox.setModel(carreraModel);
        turnoComboBox.setModel(turnoModel);
        cicloJComboBox.setModel(cicloModel);
        SemestrecomboBox.setModel(semestreModel);
        GrupoComboBox.setModel(grupoModel);
        jTabbedPane1.addChangeListener(new ChangeListener() {
            @Override
        public void stateChanged(ChangeEvent ce) {
            if(ce.getSource() instanceof JTabbedPane) {
                JTabbedPane pane = (JTabbedPane)ce.getSource();
                System.out.println("Selected pane NO: " + pane.getSelectedIndex());
                LlenarLista();
                } 
            }
        });
        try {
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
             conexion = DriverManager.getConnection ("jdbc:mysql://localhost/proyecto","root", "");
            s = conexion.createStatement();
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        ButtonGroupTurno = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaEliminados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        EliminarUsuario = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TypeOfUser = new javax.swing.JList<>();
        UserTextField = new javax.swing.JTextField();
        PasswdTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        SaveUser = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CarreraComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        GrupoComboBox = new javax.swing.JComboBox<>();
        SemestrecomboBox = new javax.swing.JComboBox<>();
        turnoComboBox = new javax.swing.JComboBox<>();
        GuardarDatos = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        apellidoTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cicloJComboBox = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        alumnosRadioButton1 = new javax.swing.JRadioButton();
        docenteRadioButton1 = new javax.swing.JRadioButton();
        seRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaDatos = new javax.swing.JList<>();
        CicloDatosJLabel = new javax.swing.JLabel();
        CicloDatosTextField = new javax.swing.JTextField();
        SemestreDatosJlabel = new javax.swing.JLabel();
        TurnoDatosJlabel = new javax.swing.JLabel();
        CarreraDatosJlabel = new javax.swing.JLabel();
        TurnoDatosJtext = new javax.swing.JTextField();
        SemestreDatosTextField = new javax.swing.JTextField();
        CarreraDatosTextField = new javax.swing.JTextField();
        GrupoDatosJLabel = new javax.swing.JLabel();
        GrupoDatosTextfield = new javax.swing.JTextField();
        nombreJlabelDatos = new javax.swing.JLabel();
        nombreDatosTextField = new javax.swing.JTextField();
        ApellidoDatosJlabel = new javax.swing.JLabel();
        ApellidoDatosJText = new javax.swing.JTextField();
        MatriculaDatosJLabel = new javax.swing.JLabel();
        MatriculaDatosJtext = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Administrador");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jButton2.setText("Cerrar Sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(466, 466, 466))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Name)
                .addGap(230, 230, 230)
                .addComponent(jButton2))
        );

        jTabbedPane1.addTab("Inicio", jPanel1);

        ListaEliminados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaEliminados.setSelectedIndex(0);
        jScrollPane2.setViewportView(ListaEliminados);

        jLabel1.setText("Nombre de Usuario");

        EliminarUsuario.setText("Eliminar");
        EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar Sesion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EliminarUsuario)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(EliminarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Eliminar Usuario", jPanel3);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.setLayout(null);

        jLabel2.setText("Usuario:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 29, 70, 14);

        jLabel3.setText("Contraseña:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 87, 90, 14);

        jLabel4.setText("Tipo Usuario:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 143, 63, 14);

        TypeOfUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Alumno", "Docente", "Servicios Academicos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TypeOfUser.setSelectedIndex(0);
        jScrollPane1.setViewportView(TypeOfUser);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 168, 150, 74);

        UserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(UserTextField);
        UserTextField.setBounds(10, 54, 110, 20);
        jPanel2.add(PasswdTextField);
        PasswdTextField.setBounds(10, 112, 110, 20);

        jButton3.setText("Cerrar Sesion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(10, 266, 150, 23);

        SaveUser.setText("Guardar");
        SaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveUserActionPerformed(evt);
            }
        });
        jPanel2.add(SaveUser);
        SaveUser.setBounds(190, 270, 110, 23);

        Reset.setText("Restablecer");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel2.add(Reset);
        Reset.setBounds(310, 270, 130, 23);

        jLabel10.setVisible(false);
        jLabel10.setText("Turno:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(190, 130, 40, 14);

        jLabel11.setVisible(false);
        jLabel11.setText("Semestre:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(190, 150, 60, 14);

        jLabel12.setVisible(false);
        jLabel12.setText("Carrera:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(190, 190, 41, 14);

        CarreraComboBox.setVisible(false);
        CarreraComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CarreraComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarreraComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(CarreraComboBox);
        CarreraComboBox.setBounds(260, 190, 130, 20);

        jLabel13.setVisible(false);
        jLabel13.setText("Grupo");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(190, 170, 29, 14);

        GrupoComboBox.setVisible(false);
        GrupoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        jPanel2.add(GrupoComboBox);
        GrupoComboBox.setBounds(260, 170, 90, 20);

        SemestrecomboBox.setVisible(false);
        SemestrecomboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel2.add(SemestrecomboBox);
        SemestrecomboBox.setBounds(260, 150, 130, 20);

        turnoComboBox.setVisible(false);
        turnoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(turnoComboBox);
        turnoComboBox.setBounds(260, 130, 130, 20);

        GuardarDatos.setVisible(false);
        GuardarDatos.setText("Guardar");
        GuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatosActionPerformed(evt);
            }
        });
        jPanel2.add(GuardarDatos);
        GuardarDatos.setBounds(190, 230, 110, 23);

        jLabel14.setVisible(false);
        jLabel14.setText("Nombre:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(190, 20, 60, 14);

        nombreTextField.setVisible(false);
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nombreTextField);
        nombreTextField.setBounds(260, 20, 130, 20);

        jLabel15.setVisible(false);
        jLabel15.setText("Apellido:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(190, 60, 41, 14);

        apellidoTextField.setVisible(false);
        jPanel2.add(apellidoTextField);
        apellidoTextField.setBounds(260, 60, 130, 20);

        jLabel16.setVisible(false);
        jLabel16.setText("Ciclo:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(190, 110, 40, 14);

        cicloJComboBox.setVisible(false);
        cicloJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cicloJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicloJComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(cicloJComboBox);
        cicloJComboBox.setBounds(260, 110, 130, 20);

        jLabel17.setVisible(false);
        jLabel17.setText("Matricula");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(190, 90, 63, 14);

        matriculaTextField.setVisible(false);
        matriculaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaTextFieldActionPerformed(evt);
            }
        });
        matriculaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculaTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matriculaTextFieldKeyTyped(evt);
            }
        });
        jPanel2.add(matriculaTextField);
        matriculaTextField.setBounds(260, 90, 130, 20);

        jTabbedPane1.addTab("Nuevo Usuario", jPanel2);

        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 600));

        alumnosRadioButton1.setText("alumnos");
        alumnosRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnosRadioButton1ActionPerformed(evt);
            }
        });

        docenteRadioButton1.setText("Docentes");
        docenteRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docenteRadioButton1ActionPerformed(evt);
            }
        });

        seRadioButton1.setText("Servicios Escolares");
        seRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seRadioButton1ActionPerformed(evt);
            }
        });

        ListaDatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDatosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ListaDatos);

        CicloDatosJLabel.setText("Ciclo");

        CicloDatosTextField.setEditable(false);

        SemestreDatosJlabel.setText("Semestre");

        TurnoDatosJlabel.setText("Turno");

        CarreraDatosJlabel.setText("Carrera");

        TurnoDatosJtext.setEditable(false);

        SemestreDatosTextField.setEditable(false);

        CarreraDatosTextField.setEditable(false);

        GrupoDatosJLabel.setText("Grupo");

        GrupoDatosTextfield.setEditable(false);

        nombreJlabelDatos.setText("Nombre");

        nombreDatosTextField.setEditable(false);

        ApellidoDatosJlabel.setText("Apellido");

        ApellidoDatosJText.setEditable(false);

        MatriculaDatosJLabel.setText("Matricula");

        MatriculaDatosJtext.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(alumnosRadioButton1)
                .addGap(45, 45, 45)
                .addComponent(docenteRadioButton1)
                .addGap(39, 39, 39)
                .addComponent(seRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(nombreJlabelDatos)
                .addGap(63, 63, 63)
                .addComponent(ApellidoDatosJlabel))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculaDatosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculaDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SemestreDatosJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SemestreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CicloDatosJLabel))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ApellidoDatosJText, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurnoDatosJlabel)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GrupoDatosJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrupoDatosTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarreraDatosJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarreraDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(CicloDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TurnoDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alumnosRadioButton1)
                    .addComponent(docenteRadioButton1)
                    .addComponent(seRadioButton1))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreJlabelDatos)
                    .addComponent(ApellidoDatosJlabel))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nombreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(MatriculaDatosJLabel)
                        .addGap(6, 6, 6)
                        .addComponent(MatriculaDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(SemestreDatosJlabel)
                        .addGap(6, 6, 6)
                        .addComponent(SemestreDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CicloDatosJLabel))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ApellidoDatosJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(GrupoDatosJLabel)
                        .addGap(6, 6, 6)
                        .addComponent(GrupoDatosTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CarreraDatosJlabel)
                        .addGap(6, 6, 6)
                        .addComponent(CarreraDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(TurnoDatosJlabel)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CicloDatosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TurnoDatosJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Consulta datos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void matriculaTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculaTextFieldKeyTyped
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||(caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)){
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_matriculaTextFieldKeyTyped

    private void matriculaTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculaTextFieldKeyPressed

    }//GEN-LAST:event_matriculaTextFieldKeyPressed

    private void matriculaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaTextFieldActionPerformed

    }//GEN-LAST:event_matriculaTextFieldActionPerformed

    private void cicloJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicloJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cicloJComboBoxActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void GuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatosActionPerformed

        InsertarDatos(Type);
    }//GEN-LAST:event_GuardarDatosActionPerformed

    private void CarreraComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarreraComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarreraComboBoxActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        UserTextField.setText("");
        PasswdTextField.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void SaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveUserActionPerformed
        user = UserTextField.getText();
        passwd = PasswdTextField.getText();
        Type = TypeOfUser.getSelectedIndex() + 2;
        llenarCombo();
           JOptionPane.showMessageDialog(this, "Usuario Agregado con exito, ingrese los datos a continuacion", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
         try {
                Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
                RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");
                a.insertarUsuario(user, passwd, Type);
            }catch (Exception e) {
                System.err.println("El servidor no esta prendido "+ e);
            }
        switch(Type){
            case 2:
            UserTextField.setText("");
            PasswdTextField.setText("");
            UserTextField.setVisible(false);
            PasswdTextField.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jScrollPane1.setVisible(false);
            SaveUser.setVisible(false);
            TypeOfUser.setVisible(false);
            Reset.setVisible(false);
            jLabel11.setVisible(true);
            turnoComboBox.setVisible(true);
            jLabel10.setVisible(true);
            SemestrecomboBox.setVisible(true);
            cicloJComboBox.setVisible(true);
            jLabel13.setVisible(true);
            GrupoComboBox.setVisible(true);
            jLabel12.setVisible(true);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            jLabel16.setVisible(true);
            jLabel17.setVisible(true);
            matriculaTextField.setVisible(true);
            nombreTextField.setVisible(true);
            apellidoTextField.setVisible(true);
            CarreraComboBox.setVisible(true);
            GuardarDatos.setVisible(true);
            break;
            case 3:
            UserTextField.setText("");
            PasswdTextField.setText("");
            UserTextField.setVisible(false);
            PasswdTextField.setVisible(false);
            SemestrecomboBox.setVisible(true);
            jLabel13.setVisible(true);
            GrupoComboBox.setVisible(true);

            jLabel11.setVisible(true);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jScrollPane1.setVisible(false);
            SaveUser.setVisible(false);
            TypeOfUser.setVisible(false);
            Reset.setVisible(false);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            jLabel17.setVisible(true);
            nombreTextField.setVisible(true);
            apellidoTextField.setVisible(true);
            matriculaTextField.setVisible(true);
            GuardarDatos.setVisible(true);
            break;
            case 4:
            UserTextField.setText("");
            PasswdTextField.setText("");
            UserTextField.setVisible(false);
            PasswdTextField.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jScrollPane1.setVisible(false);
            SaveUser.setVisible(false);
            TypeOfUser.setVisible(false);
            Reset.setVisible(false);
            jLabel14.setVisible(true);
            jLabel15.setVisible(true);
            nombreTextField.setVisible(true);
            apellidoTextField.setVisible(true);
            GuardarDatos.setVisible(true);
            break;
        }
    }//GEN-LAST:event_SaveUserActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTextFieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioActionPerformed
        String eliminacion = ListaEliminados.getSelectedValue();
        if (JOptionPane.showConfirmDialog(this, "En verdad desea eliminar el usuario: " + eliminacion, "Confirmacion", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try {
                Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
                RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");
                a.eliminar(eliminacion);
                a.cerrarConexion();
            }catch (Exception e) {
                System.err.println("El servidor no esta prendido ");
            }
            JOptionPane.showMessageDialog(this, "Usuario Eliminado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
            
            LlenarLista();

        }
    }//GEN-LAST:event_EliminarUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void alumnosRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnosRadioButton1ActionPerformed
        tipoUsuario = 2;
        nombreDatosTextField.setText("");
        ApellidoDatosJText.setText("");
        MatriculaDatosJtext.setText("");
        GrupoDatosTextfield.setText("");
        CarreraDatosTextField.setText("");
        SemestreDatosTextField.setText("");
        CicloDatosTextField.setText("");
        TurnoDatosJtext.setText("");
        SemestreDatosJlabel.setVisible(true);
        SemestreDatosTextField.setVisible(true);
        GrupoDatosJLabel.setVisible(true);
        GrupoDatosTextfield.setVisible(true);
        SemestreDatosJlabel.setVisible(true);
        SemestreDatosTextField.setVisible(true);
        CarreraDatosJlabel.setVisible(true);
        CarreraDatosTextField.setVisible(true);
        CicloDatosJLabel.setVisible(true);
        CicloDatosTextField.setVisible(true);
        TurnoDatosJlabel.setVisible(true);
        TurnoDatosJtext.setVisible(true);
        LlenarListaDatos(tipoUsuario);
    }//GEN-LAST:event_alumnosRadioButton1ActionPerformed

    private void docenteRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docenteRadioButton1ActionPerformed
        tipoUsuario = 3;
        nombreDatosTextField.setText("");
        ApellidoDatosJText.setText("");
        MatriculaDatosJtext.setText("");
        GrupoDatosTextfield.setText("");
        SemestreDatosJlabel.setVisible(true);
        SemestreDatosTextField.setVisible(true);
        CarreraDatosJlabel.setVisible(true);
        CarreraDatosTextField.setVisible(true);
        CicloDatosJLabel.setVisible(false);
        CicloDatosTextField.setVisible(false);
        TurnoDatosJlabel.setVisible(false);
        TurnoDatosJtext.setVisible(false);
        LlenarListaDatos(tipoUsuario);

    }//GEN-LAST:event_docenteRadioButton1ActionPerformed

    private void seRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seRadioButton1ActionPerformed
        tipoUsuario = 4;
        nombreDatosTextField.setText("");
        ApellidoDatosJText.setText("");
        MatriculaDatosJtext.setText("");
        GrupoDatosJLabel.setVisible(false);
        GrupoDatosTextfield.setVisible(false);
        GrupoDatosJLabel.setVisible(false);
        GrupoDatosTextfield.setVisible(false);
        SemestreDatosJlabel.setVisible(false);
        SemestreDatosTextField.setVisible(false);
        CarreraDatosJlabel.setVisible(false);
        CarreraDatosTextField.setVisible(false);
        CicloDatosJLabel.setVisible(false);
        CicloDatosTextField.setVisible(false);
        TurnoDatosJlabel.setVisible(false);
        TurnoDatosJtext.setVisible(false);
        LlenarListaDatos(tipoUsuario);

    }//GEN-LAST:event_seRadioButton1ActionPerformed

    private void ListaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDatosMouseClicked
        String nomb = (String)ListaDatos.getSelectedValue();
        ConsultarDatos(nomb, tipoUsuario);

    }//GEN-LAST:event_ListaDatosMouseClicked

    private Connection conexion(){
        try{
            Connection conexion = DriverManager.getConnection ("jdbc:mysql://localhost/proyecto","root", "");
            return  conexion;
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error de conexión", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
    
   public void llenarCombo(){
        try {
            Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
            try {
                Connection conexion = conexion();
                Statement s = conexion.createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM carrera");
                while(rs.next()) {
                   carreraModel.addElement(rs.getString(2));
                }
                rs = s.executeQuery("SELECT * FROM turnos");
                while(rs.next()) {
                   turnoModel.addElement(rs.getString(2));
                }
                rs = s.executeQuery("SELECT * FROM ciclo");
                while(rs.next()) {
                   cicloModel.addElement(rs.getString(2));
                }
                rs = s.executeQuery("SELECT * FROM semestre");
                while(rs.next()) {
                   semestreModel.addElement(rs.getString(2));
                }
                rs = s.executeQuery("SELECT * FROM grupos");
                while(rs.next()) {
                   grupoModel.addElement(rs.getString(2));
                }
            } catch (SQLException e) {
            }

        } catch (Exception e) {
            System.err.println("El servidor no esta prendido ");
        }
     }
    
    private void LlenarLista(){
        try {
            model.clear();
            Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");
            try {
                Connection conexion = conexion();
                Statement s = conexion.createStatement();
                ResultSet rs = s.executeQuery("SELECT * FROM usuarios");
                while(rs.next())
                    model.addElement(rs.getString(2));
            } catch (SQLException e) {
            }

        }catch (Exception e) {   
            System.err.println("El servidor no esta prendido ");
        }
    }
     private void LlenarListaDatos(int dato){
        try{
            model2.clear();
            Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
            Connection conexion = conexion();
            Statement s = conexion.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM usuarios WHERE tipo_usuario= '"+dato+"' ");
            while(rs.next()) 
                model2.addElement(rs.getString(2));
        }catch (Exception e) {   
            System.err.println("El servidor no esta prendido ");
        }
        
    }
     
     
     private void InsertarDatos(int tipo){
         ArrayList al = new ArrayList();
        try {
            String usernew = user;
            Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
            al = a.login(user, passwd);
            id_alumno = (int)al.get(0);
        }catch (Exception e) {   
            System.err.println("El servidor no esta prendido "+ e);
        }               
        nombre = nombreTextField.getText();
        apellido =  apellidoTextField.getText(); 
        switch(tipo){
            case 2:
                matricula = Integer.parseInt(matriculaTextField.getText());
                grupo = GrupoComboBox.getSelectedIndex() +1 ;
                semestre = SemestrecomboBox.getSelectedIndex() + 1;
                carrera = CarreraComboBox.getSelectedIndex() + 1;
                ciclo = cicloJComboBox.getSelectedIndex() +1;
                turno = turnoComboBox.getSelectedIndex() + 1;
                try {
                    Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
                    RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
                    a.insertarAlumno(id_alumno, nombre, apellido, matricula, grupo, semestre, carrera, ciclo, turno);
                    JOptionPane.showMessageDialog(this, "Alumno Agregado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {   
                    System.err.println("El servidor no esta prendido " +e);
                }
                break;
            case 3:         
                matricula = Integer.parseInt(matriculaTextField.getText());
                grupo = GrupoComboBox.getSelectedIndex() +1 ;
                semestre = SemestrecomboBox.getSelectedIndex() + 1;
                try {
                    Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
                    RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
                    a.insertarMaestro(id_alumno, nombre, apellido, matricula, grupo, semestre);
                    JOptionPane.showMessageDialog(this, "Maestro Agregado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
                }catch (Exception e) {   
                    System.err.println("El servidor no esta prendido ");
                }
                 break;
             case 4:
                try {
                    Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
                    RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");    
                    a.insertarServe(id_alumno, nombre, apellido);
                    JOptionPane.showMessageDialog(this, "Servicios Escolares Agregado con exito", "Aceptado", JOptionPane.INFORMATION_MESSAGE);
                }catch (Exception e) {   
                    System.err.println("El servidor no esta prendido ");
                }
                break;
         }
     }
     public void llenarComboBox(){
          try {
            ResultSet rs = s.executeQuery("SELECT * FROM carrera");
            while(rs.next()) {
               carreraModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
           try {
            
            ResultSet rs = s.executeQuery("SELECT * FROM turnos");
            while(rs.next()) {
               turnoModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
             try {
           
            ResultSet rs = s.executeQuery("SELECT * FROM ciclo");
            while(rs.next()) {
               cicloModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
                try {
           
            ResultSet rs = s.executeQuery("SELECT * FROM semestre");
            while(rs.next()) {
               semestreModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
                     try {
           
            ResultSet rs = s.executeQuery("SELECT * FROM grupos");
            while(rs.next()) {
               grupoModel.addElement(rs.getString(2));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
     }
       public void ConsultarDatos(String nomb, int tipoUsuarioDatos){
        ArrayList al = new ArrayList();
         int id = 0, Dgrupo = 0, Dsemestre= 0, Dcarrera = 0, Dciclo = 0, Dturno = 0;
         switch(tipoUsuarioDatos){
             case 2:
              al.clear();      
            try {
                
             Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
            al = a.retornodeUsuario(nomb);
            id = (int)al.get(0);
            }
            catch (Exception e) {   
                    System.err.println("El servidor no esta prendido " +e);
               }
            try {
                al.clear();
                ArrayList al2 = new ArrayList();
             Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
            al = a.retornodeAlumno(id);
                nombreDatosTextField.setText(al.get(0).toString());
                ApellidoDatosJText.setText(al.get(1).toString());
                MatriculaDatosJtext.setText(al.get(2).toString());
                al2 = a.datosAlumno((int)al.get(3), (int)al.get(4), (int)al.get(5),(int) al.get(6), (int)al.get(7));
                GrupoDatosTextfield.setText(al2.get(0).toString());
                CarreraDatosTextField.setText(al2.get(1).toString());
                SemestreDatosTextField.setText(al2.get(2).toString());
                CicloDatosTextField.setText(al2.get(3).toString());
                TurnoDatosJtext.setText(al2.get(4).toString());
            }
            catch (Exception e) {   
                    System.err.println("El servidor no esta prendido " +e);
               }
      
                 break;
             case 3:
                 al.clear();
               try {
             Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
            al = a.retornodeUsuario(nomb);
            id = (int)al.get(0);
            al.clear();
            al = a.retornodeDocente(id);
            }
            catch (Exception e) {   
                    System.err.println("El servidor no esta prendido " +e);
               }    
            nombreDatosTextField.setText(al.get(0).toString());
            ApellidoDatosJText.setText(al.get(1).toString());
            MatriculaDatosJtext.setText(al.get(2).toString());
            GrupoDatosTextfield.setText(al.get(3).toString());
            break;
             case 4:
            al.clear();
            try {
            Registry MiRegistro = LocateRegistry.getRegistry("127.0.0.1", 1234);
            RemoteInterface a = (RemoteInterface) MiRegistro.lookup("SE");  
            al = a.retornodeUsuario(nomb);
            id = (int)al.get(0);
            al.clear();
            al = a.retornodeServe(id);
            }
            catch (Exception e) {   
                    System.err.println("El servidor no esta prendido " +e);
               }             
           
                nombreDatosTextField.setText(al.get(0).toString());
                ApellidoDatosJText.setText(al.get(1).toString());
                 break;
         }
     }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoDatosJText;
    private javax.swing.JLabel ApellidoDatosJlabel;
    private javax.swing.ButtonGroup ButtonGroupTurno;
    private javax.swing.JComboBox<String> CarreraComboBox;
    private javax.swing.JLabel CarreraDatosJlabel;
    private javax.swing.JTextField CarreraDatosTextField;
    private javax.swing.JLabel CicloDatosJLabel;
    private javax.swing.JTextField CicloDatosTextField;
    private javax.swing.JButton EliminarUsuario;
    private javax.swing.JComboBox<String> GrupoComboBox;
    private javax.swing.JLabel GrupoDatosJLabel;
    private javax.swing.JTextField GrupoDatosTextfield;
    private javax.swing.JButton GuardarDatos;
    private javax.swing.JList<String> ListaDatos;
    private javax.swing.JList<String> ListaEliminados;
    private javax.swing.JLabel MatriculaDatosJLabel;
    private javax.swing.JTextField MatriculaDatosJtext;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField PasswdTextField;
    private javax.swing.JButton Reset;
    private javax.swing.JButton SaveUser;
    private javax.swing.JLabel SemestreDatosJlabel;
    private javax.swing.JTextField SemestreDatosTextField;
    private javax.swing.JComboBox<String> SemestrecomboBox;
    private javax.swing.JLabel TurnoDatosJlabel;
    private javax.swing.JTextField TurnoDatosJtext;
    private javax.swing.JList<String> TypeOfUser;
    private javax.swing.JTextField UserTextField;
    private javax.swing.JRadioButton alumnosRadioButton1;
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cicloJComboBox;
    private javax.swing.JRadioButton docenteRadioButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JTextField nombreDatosTextField;
    private javax.swing.JLabel nombreJlabelDatos;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JRadioButton seRadioButton1;
    private javax.swing.JComboBox<String> turnoComboBox;
    // End of variables declaration//GEN-END:variables
}
