# Generated by Django 2.0.6 on 2018-07-17 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstatusIncidencia',
            fields=[
                ('id_estatus', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('fecha_incidencia', models.DateTimeField()),
                ('asunto', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=500)),
                ('id_estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencia.EstatusIncidencia')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIndicencia',
            fields=[
                ('id_tipo', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('impacto', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='incidencia',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencia.TipoIndicencia'),
        ),
    ]
