# Generated by Django 2.0.6 on 2018-07-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidencia',
            old_name='id_estatus',
            new_name='estatus',
        ),
        migrations.RenameField(
            model_name='incidencia',
            old_name='id_tipo',
            new_name='tipo',
        ),
    ]
