# Generated by Django 2.0.7 on 2018-07-26 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_auto_20180717_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencia.EstatusIncidencia'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidencia.TipoIndicencia'),
        ),
    ]
