# Generated by Django 2.0.7 on 2018-07-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20180726_2321'),
        ('cita', '0004_auto_20180726_2257'),
        ('incidencia', '0003_auto_20180726_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ManyToManyField(to='incidencia.Comentario')),
                ('persona', models.ManyToManyField(to='usuario.Docente')),
                ('rel', models.ManyToManyField(to='cita.Cita')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia_alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ManyToManyField(to='usuario.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia_cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ManyToManyField(to='cita.Cita')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia_docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ManyToManyField(to='usuario.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia_padre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estatus',
            field=models.CharField(choices=[('1', 'Reportada'), ('2', 'En Proceso'), ('3', 'Atendida'), ('4', 'Otro')], default='1', max_length=2),
        ),
        migrations.DeleteModel(
            name='EstatusIncidencia',
        ),
        migrations.AddField(
            model_name='incidencia_padre',
            name='incidencia',
            field=models.ManyToManyField(to='incidencia.Incidencia'),
        ),
        migrations.AddField(
            model_name='incidencia_padre',
            name='padre',
            field=models.ManyToManyField(to='usuario.Padre_Familia'),
        ),
        migrations.AddField(
            model_name='incidencia_docente',
            name='incidencia',
            field=models.ManyToManyField(to='incidencia.Incidencia'),
        ),
        migrations.AddField(
            model_name='incidencia_cita',
            name='incidencia',
            field=models.ManyToManyField(to='incidencia.Incidencia'),
        ),
        migrations.AddField(
            model_name='incidencia_alumno',
            name='incidencia',
            field=models.ManyToManyField(to='incidencia.Incidencia'),
        ),
    ]
