# Generated by Django 2.0.7 on 2018-07-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0004_auto_20180726_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario_rel',
            name='comentario',
            field=models.ManyToManyField(blank=True, to='incidencia.Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario_rel',
            name='persona',
            field=models.ManyToManyField(blank=True, to='usuario.Docente'),
        ),
        migrations.AlterField(
            model_name='comentario_rel',
            name='rel',
            field=models.ManyToManyField(blank=True, to='cita.Cita'),
        ),
        migrations.AlterField(
            model_name='incidencia_alumno',
            name='alumno',
            field=models.ManyToManyField(blank=True, to='usuario.Alumno'),
        ),
        migrations.AlterField(
            model_name='incidencia_alumno',
            name='incidencia',
            field=models.ManyToManyField(blank=True, to='incidencia.Incidencia'),
        ),
        migrations.AlterField(
            model_name='incidencia_cita',
            name='cita',
            field=models.ManyToManyField(blank=True, to='cita.Cita'),
        ),
        migrations.AlterField(
            model_name='incidencia_cita',
            name='incidencia',
            field=models.ManyToManyField(blank=True, to='incidencia.Incidencia'),
        ),
        migrations.AlterField(
            model_name='incidencia_docente',
            name='docente',
            field=models.ManyToManyField(blank=True, to='usuario.Docente'),
        ),
        migrations.AlterField(
            model_name='incidencia_docente',
            name='incidencia',
            field=models.ManyToManyField(blank=True, to='incidencia.Incidencia'),
        ),
        migrations.AlterField(
            model_name='incidencia_padre',
            name='incidencia',
            field=models.ManyToManyField(blank=True, to='incidencia.Incidencia'),
        ),
        migrations.AlterField(
            model_name='incidencia_padre',
            name='padre',
            field=models.ManyToManyField(blank=True, to='usuario.Padre_Familia'),
        ),
    ]
