# Generated by Django 2.0.7 on 2018-07-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0005_auto_20180728_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='observaciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tipoindicencia',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
